# Canonical validation, build, and self-documentation entry points for javascript-doxygen.

SHELL := /bin/sh
.SHELLFLAGS := -eu -c

AWK_BIN ?= awk
AWK_SOURCES := $(wildcard *.awk)
SOURCE_FILTER := doxygen-javascript.awk
DOXYGEN_CONSUMER_CONFIG := doxygen-javascript.conf
INTEGRATION_CONFIG := test/doxygen/Doxyfile
INTEGRATION_OUT := test/doxygen/out
DOXYGEN_JAVASCRIPT_FILTER ?= $(SOURCE_FILTER)

DIST_DIR := dist
DIST_DEV_SCRIPT := $(DIST_DIR)/doxygen-javascript.dev.awk
DIST_SCRIPT := $(DIST_DIR)/doxygen-javascript.awk
DIST_MIN_SCRIPT := $(DIST_DIR)/doxygen-javascript.min.awk
DIST_SCRIPTS := $(DIST_DEV_SCRIPT) $(DIST_SCRIPT) $(DIST_MIN_SCRIPT)
DIST_CHECKSUMS := $(addsuffix .sha256,$(DIST_SCRIPTS))

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
DOCS_MANIFEST := dependencies-docs.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.10
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := acbe79d39ab8cbbf906bd864d410ba7a223ba6f09501c02a409b8d3aa8740462
VENDOR_AWK_FILTER := $(VENDOR_DIR)/doxygen-awk.awk
VENDOR_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
ADRCTL := $(VENDOR_DIR)/adrctl.bash
AWK_MINIFIER := $(VENDOR_DIR)/awk-minifier.awk
AWK_MINIFIER_VERSION := 0.2.1
ADR_DIR := doc/adr
ADR_INDEX_FILE := $(ADR_DIR)/README.md
ADR_INDEX_INTRO := $(ADR_DIR)/README.intro.md
ADR_INDEX_OUTRO := $(ADR_DIR)/README.outro.md
REFERENCE_DOC_DIR := doc/reference
AWK_DOXYGEN_FILTER ?= $(VENDOR_AWK_FILTER)
BASH_DOXYGEN_FILTER ?= $(VENDOR_BASH_FILTER)

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all adr-index build check checksums clean deps deps-check deps-docs deps-docs-check dist-clean distclean docs docs-canary docs-clean integration-clean test test-dist test-dist-doxygen test-doxygen test-source verify-bashdeps verify-build-deps verify-checksums FORCE

all: deps
	$(MAKE) --no-print-directory build

## Build development, ordinary, and minified filters plus adjacent SHA-256 files.
build: verify-build-deps
	$(MAKE) --no-print-directory $(DIST_SCRIPTS) $(DIST_CHECKSUMS)

## Verify prepared build dependency state without network access or repair.
verify-build-deps: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

$(DIST_DEV_SCRIPT): $(SOURCE_FILTER)
	@mkdir -p "$(DIST_DIR)"
	@{ \
		sed -n '1p' "$(SOURCE_FILTER)"; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Artifact: development'; \
		printf '%s\n' '# Version: $(VERSION)'; \
		printf '%s\n' '# Build date: $(BUILD_DATE)'; \
		printf '%s\n' '# Build commit: $(BUILD_COMMIT)'; \
		printf '%s\n' '# Source: $(SOURCE_FILTER)'; \
		printf '%s\n' '# End generated header.'; \
		printf '\n'; \
		sed '1d' "$(SOURCE_FILTER)"; \
	} >"$@.tmp"
	@chmod 0755 "$@.tmp"
	@mv "$@.tmp" "$@"

# The ordinary artifact removes only project-governed Doxygen documentation lines.
# It deliberately does not attempt general AWK comment stripping.
$(DIST_SCRIPT): $(DIST_DEV_SCRIPT)
	@sed \
		-e '/^[[:space:]]*##/d' \
		-e 's/^# Artifact: development$$/# Artifact: ordinary/' \
		"$<" >"$@.tmp"
	@chmod 0755 "$@.tmp"
	@mv "$@.tmp" "$@"

# The pinned released AWK Minifier transforms only the ordinary artifact body.
# Build provenance stays outside the transformer input so the minified artifact
# remains inspectable without asking the candidate build to minify itself.
$(DIST_MIN_SCRIPT): $(DIST_SCRIPT) $(AWK_MINIFIER)
	@input="$@.input.tmp"; body="$@.body.tmp"; \
	trap 'rm -f "$$input" "$$body" "$@.tmp"' EXIT HUP INT TERM; \
	sed '1,/^# End generated header\.$$/d' "$<" >"$$input"; \
	"$(AWK_BIN)" -f "$(AWK_MINIFIER)" <"$$input" >"$$body"; \
	{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Artifact: minified'; \
		printf '%s\n' '# Version: $(VERSION)'; \
		printf '%s\n' '# Build date: $(BUILD_DATE)'; \
		printf '%s\n' '# Build commit: $(BUILD_COMMIT)'; \
		printf '%s\n' '# Minifier: AWK Minifier v$(AWK_MINIFIER_VERSION)'; \
		printf '%s\n' '# Minifier input: doxygen-javascript.awk body'; \
		printf '%s\n' '# End generated header.'; \
		cat "$$body"; \
	} >"$@.tmp"; \
	chmod 0755 "$@.tmp"; \
	mv "$@.tmp" "$@"; \
	rm -f "$$input" "$$body"; \
	trap - EXIT HUP INT TERM

$(DIST_DIR)/%.awk.sha256: $(DIST_DIR)/%.awk
	@digest=''; \
	if command -v sha256sum >/dev/null 2>&1; then \
		digest="$$(sha256sum "$<" | awk '{print $$1}')"; \
	elif command -v shasum >/dev/null 2>&1; then \
		digest="$$(shasum -a 256 "$<" | awk '{print $$1}')"; \
	else \
		printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; \
		exit 1; \
	fi; \
	printf '%s  %s\n' "$$digest" "$(notdir $<)" >"$@.tmp"; \
	mv "$@.tmp" "$@"

checksums: build

## Verify all generated SHA-256 files against their adjacent artifacts.
verify-checksums: $(DIST_CHECKSUMS)
	@cd "$(DIST_DIR)"; \
	for checksum in $(notdir $(DIST_CHECKSUMS)); do \
		if command -v sha256sum >/dev/null 2>&1; then \
			sha256sum -c "$$checksum" >/dev/null; \
		elif command -v shasum >/dev/null 2>&1; then \
			expected="$$(awk '{print $$1}' "$$checksum")"; \
			artifact="$$(awk '{print $$2}' "$$checksum")"; \
			actual="$$(shasum -a 256 "$$artifact" | awk '{print $$1}')"; \
			[ "$$actual" = "$$expected" ] || { printf '%s\n' "Checksum mismatch: $$artifact" >&2; exit 1; }; \
		else \
			printf '%s\n' 'No SHA-256 verification command is available for build checksums' >&2; \
			exit 1; \
		fi; \
	done

## Run GNU awk lint against maintained root AWK sources.
check:
	@command -v gawk >/dev/null 2>&1 || { printf '%s\n' 'gawk is required for make check' >&2; exit 1; }
	@for source in $(AWK_SOURCES); do \
		printf '%s\n' "Linting $$source"; \
		gawk --lint=fatal -f "$$source" </dev/null >/dev/null; \
	done

test: test-source

## Run the TAP regression suite against the maintained JavaScript filter.
test-source:
	@test -f "$(SOURCE_FILTER)" || { printf '%s\n' 'Missing JavaScript Doxygen filter' >&2; exit 1; }
	DOXYGEN_JAVASCRIPT_FILTER="$(abspath $(SOURCE_FILTER))" AWK_BIN="$(AWK_BIN)" bash ./test/run-tests.sh

## Prove artifact shape, semantic parity, and checksum validity.
test-dist: build verify-checksums
	@test -x "$(DIST_DEV_SCRIPT)"
	@test -x "$(DIST_SCRIPT)"
	@test -x "$(DIST_MIN_SCRIPT)"
	@test "$$(head -n 1 "$(DIST_DEV_SCRIPT)")" = '#!/usr/bin/awk -f'
	@test "$$(head -n 1 "$(DIST_SCRIPT)")" = '#!/usr/bin/awk -f'
	@test "$$(head -n 1 "$(DIST_MIN_SCRIPT)")" = '#!/usr/bin/awk -f'
	@grep -Fxq '# Artifact: development' "$(DIST_DEV_SCRIPT)"
	@grep -Fxq '# Artifact: ordinary' "$(DIST_SCRIPT)"
	@grep -Fxq '# Artifact: minified' "$(DIST_MIN_SCRIPT)"
	@grep -Fxq '# Minifier: AWK Minifier v$(AWK_MINIFIER_VERSION)' "$(DIST_MIN_SCRIPT)"
	@grep -Eq '^[[:space:]]*##' "$(DIST_DEV_SCRIPT)"
	@if grep -Eq '^[[:space:]]*##' "$(DIST_SCRIPT)"; then \
		printf '%s\n' 'Ordinary artifact still contains AWK Doxygen documentation' >&2; \
		exit 1; \
	fi
	@for filter in $(DIST_SCRIPTS); do \
		printf '%s\n' "Testing $$filter"; \
		DOXYGEN_JAVASCRIPT_FILTER="$$(pwd)/$$filter" AWK_BIN="$(AWK_BIN)" bash ./test/run-tests.sh; \
	done

## Exercise every generated artifact through the Doxygen integration surface.
test-dist-doxygen: build
	@for filter in $(DIST_SCRIPTS); do \
		printf '%s\n' "Doxygen integration: $$filter"; \
		$(MAKE) --no-print-directory test-doxygen \
			AWK_BIN="$(AWK_BIN)" \
			DOXYGEN_JAVASCRIPT_FILTER="$$(pwd)/$$filter"; \
	done

## Exercise governed JavaScript fixtures through Doxygen with the selected filter.
test-doxygen:
	@test -f "$(DOXYGEN_JAVASCRIPT_FILTER)" || { printf '%s\n' 'Missing JavaScript Doxygen filter' >&2; exit 1; }
	@test -f "$(DOXYGEN_CONSUMER_CONFIG)" || { printf '%s\n' 'Missing JavaScript Doxygen consumer configuration' >&2; exit 1; }
	@grep -Fxq 'ALIASES += jsyields="@par Yields^^"' "$(DOXYGEN_CONSUMER_CONFIG)" || { printf '%s\n' 'Missing governed jsyields alias' >&2; exit 1; }
	@grep -Fxq 'ALIASES += jstypedef{3||}="@page \1 \2^^@par JSDoc virtual type^^Base type: \3."' "$(DOXYGEN_CONSUMER_CONFIG)" || { printf '%s\n' 'Missing governed jstypedef alias' >&2; exit 1; }
	@grep -Fxq 'ALIASES += jsproperty{3||}="@par Property: \2^^Type: \1.^^\3"' "$(DOXYGEN_CONSUMER_CONFIG)" || { printf '%s\n' 'Missing governed jsproperty alias' >&2; exit 1; }
	@grep -Fxq 'ALIASES += jscallback{2||}="@page \1 \2^^@par JSDoc callback"' "$(DOXYGEN_CONSUMER_CONFIG)" || { printf '%s\n' 'Missing governed jscallback alias' >&2; exit 1; }
	@grep -Fxq 'ALIASES += type="@par Type^^"' "$(DOXYGEN_CONSUMER_CONFIG)" || { printf '%s\n' 'Missing governed type alias' >&2; exit 1; }
	@command -v doxygen >/dev/null 2>&1 || { printf '%s\n' 'doxygen is required for make test-doxygen' >&2; exit 1; }
	$(MAKE) --no-print-directory integration-clean
	AWK_BIN="$(AWK_BIN)" DOXYGEN_JAVASCRIPT_FILTER="$(abspath $(DOXYGEN_JAVASCRIPT_FILTER))" doxygen "$(INTEGRATION_CONFIG)"
	grep -R -q '<parameterlist kind="param">' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<parametername>value</parametername>' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<parametername>strict</parametername>' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Value to normalize' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Optional.' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Default: true.' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<simplesect kind="return">' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'The canonical normalized value' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Type: string.' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<parameterlist kind="exception">' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<parametername>TypeError</parametername>' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'not a string' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<title>Yields</title>' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Type: Record.' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Validated records in source order.' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'validatedRecords' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'line="6"' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<xreftitle>Deprecated</xreftitle>' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Use formatValue instead.' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<simplesect kind="see">' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'formatValue' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<compoundname>jsdocvirtualtypeuulslelr</compoundname>' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<title>User</title>' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'JSDoc virtual type' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Base type: Object.' "$(INTEGRATION_OUT)/xml"
	grep -R -q 'Represents a user record used by formatters.' "$(INTEGRATION_OUT)/xml"
	grep -R -q '<ref refid="jsdocvirtualtypeuulslelr"' "$(INTEGRATION_OUT)/xml"
	test -f "$(INTEGRATION_OUT)/xml/jsdocvirtualtypeuulslelr.xml"
	grep -q '<title>Property: name</title>' "$(INTEGRATION_OUT)/xml/jsdocvirtualtypeuulslelr.xml"
	grep -q 'Type: string.' "$(INTEGRATION_OUT)/xml/jsdocvirtualtypeuulslelr.xml"
	grep -q 'Display name shown to readers.' "$(INTEGRATION_OUT)/xml/jsdocvirtualtypeuulslelr.xml"
	test -f "$(INTEGRATION_OUT)/xml/jsdocvirtualcallbackuhlalnldlllelr.xml"
	grep -q '<title>Handler</title>' "$(INTEGRATION_OUT)/xml/jsdocvirtualcallbackuhlalnldlllelr.xml"
	grep -q 'JSDoc callback' "$(INTEGRATION_OUT)/xml/jsdocvirtualcallbackuhlalnldlllelr.xml"
	grep -q '<parameterlist kind="param">' "$(INTEGRATION_OUT)/xml/jsdocvirtualcallbackuhlalnldlllelr.xml"
	grep -q '<parametername>value</parametername>' "$(INTEGRATION_OUT)/xml/jsdocvirtualcallbackuhlalnldlllelr.xml"
	grep -q 'Normalized value supplied to the callback.' "$(INTEGRATION_OUT)/xml/jsdocvirtualcallbackuhlalnldlllelr.xml"
	grep -q '<simplesect kind="return">' "$(INTEGRATION_OUT)/xml/jsdocvirtualcallbackuhlalnldlllelr.xml"
	grep -q 'True when the value is accepted.' "$(INTEGRATION_OUT)/xml/jsdocvirtualcallbackuhlalnldlllelr.xml"
	grep -R -q '<ref refid="jsdocvirtualcallbackuhlalnldlllelr"' "$(INTEGRATION_OUT)/xml"
	test -f "$(INTEGRATION_OUT)/xml/type_8js.xml"
	grep -q '<name>retryLimit</name>' "$(INTEGRATION_OUT)/xml/type_8js.xml"
	grep -q '<title>Type</title>' "$(INTEGRATION_OUT)/xml/type_8js.xml"
	grep -q '{number}' "$(INTEGRATION_OUT)/xml/type_8js.xml"

FORCE:

## Bootstrap only bashdeps directly, verifying pinned bytes before execution.
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			[ "$$(shasum -a 256 "$$path" | awk '{print $$1}')" = "$(BASHDEPS_SHA256)" ]; \
		else \
			return 2; \
		fi; \
	}; \
	if [ -f "$@" ] && verify_hash "$@"; then chmod 0755 "$@"; exit 0; fi; \
	tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; \
	if command -v curl >/dev/null 2>&1; then \
		curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	elif command -v wget >/dev/null 2>&1; then \
		wget -qO "$$tmp" "$(BASHDEPS_URL)"; \
	else \
		printf '%s\n' 'curl or wget is required to bootstrap bashdeps.bash' >&2; exit 1; \
	fi; \
	verify_hash "$$tmp" || { printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; exit 1; }; \
	chmod 0755 "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

## Verify the pinned bashdeps bootstrap without network access or repair.
verify-bashdeps:
	@test -x "$(BASHDEPS)" || { printf '%s\n' 'Missing or non-executable vendor/bashdeps.bash; run make deps or make deps-docs' >&2; exit 1; }
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null 2>&1 || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps or make deps-docs' >&2; exit 1; }; \
	elif command -v shasum >/dev/null 2>&1; then \
		[ "$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')" = "$(BASHDEPS_SHA256)" ] || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps or make deps-docs' >&2; exit 1; }; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; \
	fi

## Synchronize build dependencies; this target may use the network.
deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

## Verify prepared build dependencies without network access or repair.
deps-check: verify-build-deps

## Synchronize documentation-only dependencies; this target may use the network.
deps-docs: $(BASHDEPS) $(DOCS_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DOCS_MANIFEST)"

deps-docs-check: verify-bashdeps $(DOCS_MANIFEST)
	"$(BASHDEPS)" verify "$(DOCS_MANIFEST)"

## Generate the ephemeral ADR landing page from maintained framing and ADR source.
adr-index:
	@test -r "$(ADRCTL)" || { printf '%s\n' 'Missing documentation dependency vendor/adrctl.bash; run make deps-docs first' >&2; exit 1; }
	@test -r "$(ADR_INDEX_INTRO)" || { printf '%s\n' 'Missing ADR landing-page introduction' >&2; exit 1; }
	@test -r "$(ADR_INDEX_OUTRO)" || { printf '%s\n' 'Missing ADR landing-page conclusion' >&2; exit 1; }
	@tmp="$(ADR_INDEX_FILE).tmp"; \
	trap 'rm -f "$$tmp"' EXIT; \
	bash "$(ADRCTL)" generate toc -i "$(ADR_INDEX_INTRO)" -o "$(ADR_INDEX_OUTRO)" >"$$tmp"; \
	mv "$$tmp" "$(ADR_INDEX_FILE)"; \
	trap - EXIT HUP INT TERM

## Generate stable project reference documentation with pinned released filters.
docs: deps-docs-check
	$(MAKE) --no-print-directory docs-canary \
		AWK_DOXYGEN_FILTER="$(VENDOR_AWK_FILTER)" \
		BASH_DOXYGEN_FILTER="$(VENDOR_BASH_FILTER)"

## Generate project reference documentation with explicitly selected filter paths.
docs-canary:
	@test -f "$(AWK_DOXYGEN_FILTER)" || { printf '%s\n' 'Missing AWK Doxygen filter' >&2; exit 1; }
	@test -f "$(BASH_DOXYGEN_FILTER)" || { printf '%s\n' 'Missing Bash Doxygen filter' >&2; exit 1; }
	chmod 0755 "$(AWK_DOXYGEN_FILTER)" "$(BASH_DOXYGEN_FILTER)"
	"$(AWK_BIN)" -f "$(AWK_DOXYGEN_FILTER)" -- --strict --compact "$(SOURCE_FILTER)" >/dev/null
	"$(AWK_BIN)" -f "$(BASH_DOXYGEN_FILTER)" -- --strict --compact ./test/run-tests.sh >/dev/null
	$(MAKE) --no-print-directory adr-index
	$(MAKE) --no-print-directory docs-clean
	AWK_DOXYGEN_FILTER="$(abspath $(AWK_DOXYGEN_FILTER))" \
	BASH_DOXYGEN_FILTER="$(abspath $(BASH_DOXYGEN_FILTER))" \
		doxygen Doxyfile

## Remove generated JavaScript/Doxygen integration output.
integration-clean:
	rm -rf "$(INTEGRATION_OUT)"

## Remove generated distribution artifacts.
dist-clean:
	rm -rf "$(DIST_DIR)"

## Remove generated project reference documentation.
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

clean: integration-clean dist-clean docs-clean

## Remove generated reference, ADR-navigation, and dependency state.
distclean: clean
	rm -rf "$(VENDOR_DIR)"
	rm -f "$(ADR_INDEX_FILE)"